// 🏭 GENERATED WITH generate-modules-sdk
// ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
// TODO: This file should be excluded from (not only VSCode) auto-importing.
//       @see https://github.com/Microsoft/vscode/issues/40248
//       @see https://github.com/microsoft/TypeScript/issues/35395
//       @see https://stackoverflow.com/questions/47796545/how-to-disable-auto-import-from-specific-files-in-vscode
export { ArtScaler } from './30-components/ArtScaler';
export { Icon } from './30-components/menu/Icon';
export { IconColor } from './30-components/menu/IconColor';
export { IconText } from './30-components/menu/IconText';
export { Menu } from './30-components/menu/Menu';
export { Separator } from './30-components/menu/Separator';
export { CategorizedModal, CategorizedModalBody, CategorizedModalMenu } from './30-components/modal/CategorizedModal';
export { Modal } from './30-components/modal/Modal';
export { ModalFooter } from './30-components/modal/ModalFooter';
export { PageOverlay } from './30-components/modal/PageOverlay';
export { AsyncButtonComponent } from './30-components/utils/AsyncButtonComponent';
export { AsyncContentComponent } from './30-components/utils/AsyncContentComponent';
export { Clickable } from './30-components/utils/Clickable';
export { CopyComponent } from './30-components/utils/CopyComponent';
export { ErrorBoundary } from './30-components/utils/ErrorBoundary';
export { FileComponent } from './30-components/utils/FileComponent';
export { Loader } from './30-components/utils/Loader/Loader';
export { LoaderInline } from './30-components/utils/Loader/LoaderInline';
export { TextLoader } from './30-components/utils/Loader/TextLoader';
export { Obfuscate } from './30-components/utils/Obfuscate';
export { ObservableContentComponent } from './30-components/utils/ObservableContentComponent';
export { QRCode } from './30-components/utils/QRCode';
export { RefreshContentComponent } from './30-components/utils/RefreshContentComponent';
export { Script } from './30-components/utils/Script';
export { ScriptForServerRender } from './30-components/utils/ScriptForServerRender';
export { AsyncSelectComponent } from './30-components/utils/select/AsyncSelectComponent';
export { SelfUpdateContentComponent } from './30-components/utils/SelfUpdateContentComponent';
export { TestingSquare } from './30-components/utils/TestingSquare';
export { Unwrap } from './30-components/utils/Unwrap';
export { Additional } from './40-utils/Additional';
export { aggregate } from './40-utils/aggregate';
export { amIEmbededInIFrame } from './40-utils/amIEmbededInIFrame';
export { calculate } from './40-utils/calculate';
export { checkOptionsCompatibility } from './40-utils/checkOptionsCompatibility';
export { classNames } from './40-utils/classNames';
export { Color } from './40-utils/color/Color';
export { hslToRgb } from './40-utils/color/hslToRgb';
export { rgbToHsl } from './40-utils/color/rgbToHsl';
export { compareStrings } from './40-utils/compareStrings';
export { create3dRotation } from './40-utils/create3dRotation';
export { blobToDataUrl } from './40-utils/data/blobToDataUrl';
export { dataUrlToBlob } from './40-utils/data/dataUrlToBlob';
export { downloadFile } from './40-utils/data/downloadFile';
export { ObjectUrl } from './40-utils/data/ObjectUrl';
export { deepClone } from './40-utils/deepClone';
export { alertDialogue } from './40-utils/dialogues/alertDialogue';
export { confirmDialogue } from './40-utils/dialogues/confirmDialogue';
export { fileDialogue } from './40-utils/dialogues/fileDialogue';
export { promptDialogue } from './40-utils/dialogues/promptDialogue';
export { EMOJIS, EMOJIS_IN_CATHEGORIES } from './40-utils/emojis';
export { enumToArray } from './40-utils/enumToArray';
export { BoardAlreadyExistsError } from './40-utils/errors/BoardAlreadyExistsError';
export { BoardNotFoundError } from './40-utils/errors/BoardNotFoundError';
export { CollisionError } from './40-utils/errors/CollisionError';
export { errorMessageWithAdditional } from './40-utils/errors/errorMessageWithAdditional';
export { HighOrderError } from './40-utils/errors/HighOrderError';
export { meaningfullError } from './40-utils/errors/meaningfullError';
export { ModuleNotFoundError } from './40-utils/errors/ModuleNotFoundError';
export { NotBoardError } from './40-utils/errors/NotBoardError';
export { NotFoundError } from './40-utils/errors/NotFoundError';
export { escapeRegExp } from './40-utils/escapeRegExp';
export { amendPropperFileTypeAndName } from './40-utils/files/amendPropperFileTypeAndName';
export { fetchAsFile } from './40-utils/files/fetchAsFile';
export { fetchProxied } from './40-utils/files/fetchProxied';
export { findPropperFileType } from './40-utils/files/findPropperFileType';
export { isFileExecutable } from './40-utils/files/isFileExecutable';
export { filterWithLimit } from './40-utils/filterWithLimit';
export { fitInside } from './40-utils/fitInside';
export { flatternArray } from './40-utils/flatternArray';
export { flipNegativeSize } from './40-utils/flipNegativeSize';
export { FunctionCache } from './40-utils/FunctionCache';
export { windowSize } from './40-utils/getWindowSize';
export { factor, NOT_CONSTRUCTABLE } from './40-utils/IFactory';
export { factorWithSystems } from './40-utils/IFactoryWithSystems';
export { addWhiteBackground } from './40-utils/image/addWhiteBackground';
export { createPreviewElement } from './40-utils/image/createPreviewElement';
export { imageToCanvas } from './40-utils/image/imageToCanvas';
export { measureImageSize } from './40-utils/image/measureImageSize';
export { preview } from './40-utils/image/preview';
export { isEmoji } from './40-utils/isEmoji';
export { isEqualArray } from './40-utils/isEqualArray';
export { isFetchable } from './40-utils/isFetchable';
export { isNumeric } from './40-utils/isNumeric';
export { isRunningOnLocalhost } from './40-utils/isRunningOnLocalhost';
export { isValidDataUrl } from './40-utils/isValidDataUrl';
export { isValidUriId } from './40-utils/isValidUriId';
export { isValidUrl } from './40-utils/isValidUrl';
export { isValidUuid } from './40-utils/isValidUuid';
export { joinWithAny } from './40-utils/joinWithJsx';
export { compareJsxs } from './40-utils/jsx-html/compareJsxs';
export { jsxToHtml } from './40-utils/jsx-html/jsxToHtml';
export { jsxToHtmlPretty } from './40-utils/jsx-html/jsxToHtmlPretty';
export { jsxToHtmlSimple } from './40-utils/jsx-html/jsxToHtmlSimple';
export { jsxToText } from './40-utils/jsx-html/jsxToText';
export { loadAndRunExternalScript } from './40-utils/loadAndRunExternalScript';
export { nextWithMutation } from './40-utils/nextWithMutation';
export { capitalize } from './40-utils/normalizing/capitalize';
export { decapitalize } from './40-utils/normalizing/decapitalize';
export { nameToUriPart } from './40-utils/normalizing/nameToUriPart';
export { normalizeToKebabCase } from './40-utils/normalizing/normalize-to-kebab-case';
export { normalizeToCamelCase } from './40-utils/normalizing/normalizeToCamelCase';
export { normalizeToSCREAMING_CASE } from './40-utils/normalizing/normalizeToSCREAMING_CASE';
export { parseKeywords } from './40-utils/normalizing/parseKeywords';
export { removeDiacritics } from './40-utils/normalizing/removeDiacritics';
export { searchKeywords } from './40-utils/normalizing/searchKeywords';
export { parseModuleName } from './40-utils/parseModuleName';
export { patternToRegExp } from './40-utils/patternToRegExp';
export { pickKeys } from './40-utils/pickKeys';
export { randomEmoji } from './40-utils/randomEmoji';
export { randomItem } from './40-utils/randomItem';
export { randomJavascriptName } from './40-utils/randomJavascriptName';
export { randomString } from './40-utils/randomString';
export { randomUriId } from './40-utils/randomUriId';
export { Editable } from './40-utils/react-components/Editable';
export { InnerHtml } from './40-utils/react-components/InnerHtml';
export { Measure } from './40-utils/react-components/Measure';
export { NonBrakingSpaces } from './40-utils/react-components/NonBrakingSpaces';
export { StaticRender } from './40-utils/react-components/StaticRender';
export { useAsyncMemo } from './40-utils/react-hooks/useAsyncMemo';
export { IUseLoadableResultStatus, useLoadable } from './40-utils/react-hooks/useLoadable';
export { useMeasure } from './40-utils/react-hooks/useMeasure';
export { useObservable } from './40-utils/react-hooks/useObservable';
export { usePromise } from './40-utils/react-hooks/usePromise';
export { useSkin } from './40-utils/react-hooks/useSkin';
export { SystemsContainerContext, useSystems } from './40-utils/react-hooks/useSystems';
export { removeKeys } from './40-utils/removeKeys';
export { requireValue } from './40-utils/requireValue';
export { scrapeContentFromUrl, scrapeContentFromUrlUncached } from './40-utils/scrapeContentFromUrl';
export { difference } from './40-utils/sets/difference';
export { union } from './40-utils/sets/union';
export { Speech } from './40-utils/Speech';
export { splitArray } from './40-utils/splitArray';
export { splitArrayIntoChunks } from './40-utils/splitArrayIntoChunks';
export { parseStyles } from './40-utils/style/css-object/parseStyles';
export { stringifyStyles } from './40-utils/style/css-object/stringifyStyles';
export { parseGlobalStyles } from './40-utils/style/global/parseGlobalStyles';
export { extractUsedSelectorsFromHtml } from './40-utils/style/misc/extractUsedSelectorsFromHtml';
export { insertStyleIntoHtml } from './40-utils/style/misc/insertStyleIntoHtml';
export { pointsToPolygon } from './40-utils/svgUtils';
export { Queue } from './40-utils/tasks/Queue';
export { ThrottleQueue } from './40-utils/tasks/ThrottleQueue';
export { ThrottleQueues } from './40-utils/tasks/ThrottleQueues';
export { toArray } from './40-utils/toArray';
export { toString } from './40-utils/toString';
export { Core } from './50-systems/30-Core/0-Core';
export { ApiClient } from './50-systems/ApiClient/0-ApiClient';
export { BoardApiClient } from './50-systems/ApiClient/BoardApiClient';
export { AppState } from './50-systems/AppState/0-AppState';
export { MaterialArtVersioningSystem } from './50-systems/ArtVersionSystem/0-MaterialArtVersioningSystem';
export { VirtualArtVersioningSystem } from './50-systems/ArtVersionSystem/0-VirtualArtVersioningSystem';
export { AttributesSystem } from './50-systems/AttributesSystem/0-AttributesSystem';
export { BoardSystem } from './50-systems/BoardSystem/0-BoardSystem';
export { BusinessSystem } from './50-systems/BusinessSystem/0-BusinessSystem';
export { BusinessName } from './50-systems/BusinessSystem/configuration/BusinessName';
export { ClosePreventionSystem } from './50-systems/ClosePreventionSystem/0-ClosePreventionSystem';
export { FakeClosePreventionSystem } from './50-systems/ClosePreventionSystem/FakeClosePreventionSystem';
export { CollSpace } from './50-systems/CollSpace/0-CollSpace';
export { ArtShell } from './50-systems/CollSpace/utils/ArtShell';
export { findArtElement } from './50-systems/CollSpace/utils/findArtElement';
export { findArtShellElement } from './50-systems/CollSpace/utils/findArtShellElement';
export { getBoundingClientRectWithoutTransform } from './50-systems/CollSpace/utils/getBoundingClientRectWithoutTransform';
export { ControlSystem } from './50-systems/ControlSystem/ControlSystem';
export { isEventOnBoard } from './50-systems/ControlSystem/utils/isEventOnBoard';
export { CreateSystem } from './50-systems/CreateSystem/0-CreateSystem';
export { ExportSystem } from './50-systems/ExportSystem/0-ExportSystem';
export { ExporterPickerComponent } from './50-systems/ExportSystem/components/0-ExporterPickerComponent';
export { ExportScopePickerComponent } from './50-systems/ExportSystem/components/0-ExportScopePickerComponent';
export { ExportPrepareComponent } from './50-systems/ExportSystem/components/ExportPrepareComponent';
export { ExportScopeSimple } from './50-systems/ExportSystem/interfaces/IExportScope';
export { sortArtContainersByScreenPosition } from './50-systems/ExportSystem/utils/sortArtContainersByScreenPosition';
export { FilepickSystem } from './50-systems/FilepickSystem/0-FilepickSystem';
export { FocusScopeName, FocusSystem } from './50-systems/FocusSystem/0-FocusSystem';
export { FractalSystem } from './50-systems/FractalSystem/0-FractalSystem';
export { GamificationSystem } from './50-systems/GamificationSystem/0-GamificationSystem';
export { GenerateSystem } from './50-systems/GenerateSystem/0-GenerateSystem';
export { HintSystem } from './50-systems/HintSystem/0-HintSystem';
export { IdentitySystem } from './50-systems/IdentitySystem/0-IdentitySystem';
export { ImportSystem } from './50-systems/ImportSystem/0-ImportSystem';
export { centerArts } from './50-systems/ImportSystem/utils/centerArts';
export { LicenseSystem } from './50-systems/LicenseSystem/0-LicenseSystem';
export { MessagesApiSystem } from './50-systems/MessagesApiSystem/0-MessagesApiSystem';
export { Authors } from './50-systems/ModuleStore/Authors';
export { ModuleStore } from './50-systems/ModuleStore/connectors/0-ModuleStore';
export { makeArticlesSetModule } from './50-systems/ModuleStore/makers/makeArticlesSetModule';
export { makeArtModule } from './50-systems/ModuleStore/makers/makeArtModule';
export { makeAttributeModule } from './50-systems/ModuleStore/makers/makeAttributeModule';
export { makeIconModule } from './50-systems/ModuleStore/makers/makeIconModule';
export { makeIconModuleOnModule } from './50-systems/ModuleStore/makers/makeIconModuleOnModule';
export { makeIconModuleOnRoute } from './50-systems/ModuleStore/makers/makeIconModuleOnRoute';
export { makeModalModule } from './50-systems/ModuleStore/makers/makeModalModule';
export { makeMultiModule } from './50-systems/ModuleStore/makers/makeMultiModule';
export { makeDynamicTrayModule } from './50-systems/ModuleStore/makers/makeTrayDynamicModule';
export { makeTraySimpleModule } from './50-systems/ModuleStore/makers/makeTraySimpleModule';
export { makeUserInterfaceModule } from './50-systems/ModuleStore/makers/makeUserInterfaceModule';
export { ArtSupportSyncer } from './50-systems/ModuleStore/Syncers/ArtSupportSyncer';
export { AttributeSupportSyncer } from './50-systems/ModuleStore/Syncers/AttributeSupportSyncer';
export { CornerstoneSyncer } from './50-systems/ModuleStore/Syncers/CornerstoneSyncer';
export { RouteAndBusinessSyncer } from './50-systems/ModuleStore/Syncers/RouteAndBusinessSyncer';
export { StorageSyncer } from './50-systems/ModuleStore/Syncers/StorageSyncer';
export { parseKeywordsFromManifest } from './50-systems/ModuleStore/utils/parseKeywordsFromManifest';
export { NotificationSystem } from './50-systems/NotificationSystem/0-NotificationSystem';
export { PointerSystem } from './50-systems/PointerSystem/0-PointerSystem';
export { RoutingSystem } from './50-systems/RoutingSystem/0-RoutingSystem';
export { DEFAULT_URL_VARIABLES, URI_PATTERN } from './50-systems/RoutingSystem/routePath/IUrlVariables';
export { SnapSystem } from './50-systems/SnapSystem/0-SnapSystem';
export { SoundSystem } from './50-systems/SoundSystem/0-SoundSystem';
export { StorageSystem } from './50-systems/StorageSystem/StorageSystem';
export { StyleSystem } from './50-systems/StyleSystem/0-StyleSystem';
export { makeSkinModule } from './50-systems/StyleSystem/makers/makeSkinModule';
export { TestSystem } from './50-systems/TestSystem/0-TestSystem';
export { ToolbarName, ToolbarSystem } from './50-systems/ToolbarSystem/0-ToolbarSystem';
export { TranslationsSystem } from './50-systems/TranslationsSystem/0-TranslationsSystem';
export { Translate } from './50-systems/TranslationsSystem/components/Translate';
export { UsercontentSystem } from './50-systems/UsercontentSystem/0-UsercontentSystem';
export { UserInterfaceSystem } from './50-systems/UserInterfaceSystem/0-UserInterfaceSystem';
export { UserInterfaceElementPlace } from './50-systems/UserInterfaceSystem/UserInterfaceElementPlace';
export { VoiceSystem } from './50-systems/VoiceSystem/0-VoiceSystem';
export { AbstractArt } from './71-arts/20-AbstractArt';
export { AbstractEnvironmentArt } from './71-arts/25-AbstractEnvironmentArt';
export { AbstractPlacedArt, NEAR_DISTANCE } from './71-arts/25-AbstractPlacedArt';
export { AbstractUserInterfaceArt } from './71-arts/25-AbstractUIArt';
export { Abstract2dArt } from './71-arts/26-Abstract2dArt';
export { AbstractBackgroundArt } from './71-arts/26-AbstractBackgroundArt';
export { Abstract2dBoxArt } from './71-arts/27-Abstract2dBoxArt';
export { AbstractTrayArt } from './71-arts/28-AbstractTrayArt';
export { CornerstoneArt, virtualCornerstoneArt } from './71-arts/30-CornerstoneArt';
export { DeletedArt } from './71-arts/30-DeletedArt';
export { ExportArt } from './71-arts/35-ExportArt';
export { ImportArt } from './71-arts/35-ImportArt';
export { BackgroundColorArt } from './71-arts/40-BackgroundColorArt';
export { BackgroundPatternArt } from './71-arts/40-BackgroundPatternArt';
export { BackgroundWallpaperArt } from './71-arts/40-BackgroundWallpaperArt';
export { FrameArt } from './71-arts/50-FrameArt';
export { FreehandArt } from './71-arts/50-FreehandArt';
export { HTMLArt } from './71-arts/50-HTMLArt';
export { ImageArt } from './71-arts/50-ImageArt';
export { LineArt } from './71-arts/50-LineArt';
export { LoadingArt } from './71-arts/50-LoadingArt';
export { ShapeArt, ShapeName } from './71-arts/50-ShapeArt';
export { TextArt } from './71-arts/50-TextArt/TextArt';
export { selectionToolDraggingBehavior } from './72-tools/behaviors/selectionTool/selectionToolDraggingBehavior';
export { selectionToolScalingBehavior } from './72-tools/behaviors/selectionTool/selectionToolScalingBehavior';
export { selectionToolSelectionBoxBehavior } from './72-tools/behaviors/selectionTool/selectionToolSelectionBoxBehavior';
export { selectionToolBehavior } from './72-tools/behaviors/selectionTool/_selectionToolBehavior';
export { MODULE_NAME_PATTERN, SCALE_PIXELS } from './config';
export {
    configchecker,
    destroyable,
    libraries,
    libs,
    React,
    styled,
    styledComponents,
    touchcontroller,
} from './libraries';
export type { string_icon } from './30-components/menu/icons';
export type { IIconAnonymous } from './30-components/menu/IIconAnonymous';
export type { Factory } from './40-utils/IFactory';
export type { Factorable } from './40-utils/IFactory';
export type { IFactorableWithSystems } from './40-utils/IFactoryWithSystems';
export type { IHandler } from './40-utils/IHandler';
export type { ICss } from './40-utils/style/css-object/ICss';
export type { IThrottleQueueOptions } from './40-utils/tasks/ThrottleQueue';
export type { ITrayDynamicItem } from './40-utils/trayModules/interfaces/ITrayDynamicItemTypes';
export type { ITrayDynamicItemList } from './40-utils/trayModules/interfaces/ITrayDynamicItemTypes';
export type { ITrayDynamicToolbarGroup } from './40-utils/trayModules/interfaces/ITrayDynamicItemTypes';
export type { ITrayDynamicToolbarItems } from './40-utils/trayModules/interfaces/ITrayDynamicItemTypes';
export type { ITrayDynamicItemFilter } from './40-utils/trayModules/interfaces/ITrayDynamicItemTypes';
export type { ITrayDynamicDefinition } from './40-utils/trayModules/interfaces/ITrayDynamicItemTypes';
export type { ITraySimpleDefinition } from './40-utils/trayModules/interfaces/ITraySimpleItemTypes';
export type { string_char_emoji } from './40-utils/typeAliasEmoji';
export type { string_mime_type } from './40-utils/typeAliases';
export type { string_mime_type_with_wildcard } from './40-utils/typeAliases';
export type { string_char } from './40-utils/typeAliases';
export type { string_html } from './40-utils/typeAliases';
export type { string_xml } from './40-utils/typeAliases';
export type { string_css } from './40-utils/typeAliases';
export type { string_css_property } from './40-utils/typeAliases';
export type { string_css_value } from './40-utils/typeAliases';
export type { string_css_selector } from './40-utils/typeAliases';
export type { string_url } from './40-utils/typeAliases';
export type { string_data_url } from './40-utils/typeAliases';
export type { string_href } from './40-utils/typeAliases';
export type { string_url_image } from './40-utils/typeAliases';
export type { string_uri } from './40-utils/typeAliases';
export type { string_uri_part } from './40-utils/typeAliases';
export type { string_uriid } from './40-utils/typeAliases';
export type { string_protocol } from './40-utils/typeAliases';
export type { string_hostname } from './40-utils/typeAliases';
export type { string_host } from './40-utils/typeAliases';
export type { string_email } from './40-utils/typeAliases';
export type { string_uuid } from './40-utils/typeAliases';
export type { string_uuid_cut } from './40-utils/typeAliases';
export type { string_sha256 } from './40-utils/typeAliases';
export type { string_version } from './40-utils/typeAliases';
export type { string_version_dependency } from './40-utils/typeAliases';
export type { string_file_extension } from './40-utils/typeAliases';
export type { string_file_absolute_path } from './40-utils/typeAliases';
export type { string_file_relative_path } from './40-utils/typeAliases';
export type { string_file_path } from './40-utils/typeAliases';
export type { string_folder_absolute_path } from './40-utils/typeAliases';
export type { string_folder_relative_path } from './40-utils/typeAliases';
export type { string_folder_path } from './40-utils/typeAliases';
export type { string_module_name } from './40-utils/typeAliases';
export type { string_module_category } from './40-utils/typeAliases';
export type { string_person_fullname } from './40-utils/typeAliases';
export type { string_person_profile } from './40-utils/typeAliases';
export type { IPersonProfile } from './40-utils/typeAliases';
export type { string_license } from './40-utils/typeAliases';
export type { ILicense } from './40-utils/typeAliases';
export type { IRepository } from './40-utils/typeAliases';
export type { string_keyword } from './40-utils/typeAliases';
export type { Keywords } from './40-utils/typeAliases';
export type { string_css_cursor } from './40-utils/typeAliases';
export type { string_attribute } from './40-utils/typeAliases';
export type { string_attribute_value_scope } from './40-utils/typeAliases';
export type { string_color } from './40-utils/typeAliases';
export type { ArrayFull } from './40-utils/typeHelpers';
export type { Arrayable } from './40-utils/typeHelpers';
export type { ArrayableFull } from './40-utils/typeHelpers';
export type { PromisableArray } from './40-utils/typeHelpers';
export type { ISystems } from './50-systems/00-SystemsContainer/ISystems';
export type { IKey } from './50-systems/ControlSystem/interfaces/IKey';
export type { IShortcut } from './50-systems/ControlSystem/interfaces/IShortcut';
export type { IExportScope } from './50-systems/ExportSystem/interfaces/IExportScope';
export type { IFileExportSupporterOptions } from './50-systems/ExportSystem/interfaces/IFileExportSupporterOptions';
export type { IFramable } from './50-systems/ExportSystem/interfaces/IFramable';
export type { IInstaller } from './50-systems/ModuleStore/interfaces/IInstaller';
export type { IInstallPlan } from './50-systems/ModuleStore/interfaces/IInstallPlan';
export type { IModule } from './50-systems/ModuleStore/interfaces/IModule';
export type { IModuleDefinition } from './50-systems/ModuleStore/interfaces/IModule';
export type { IModuleSetup } from './50-systems/ModuleStore/interfaces/IModule';
export type { IModuleManifest } from './50-systems/ModuleStore/interfaces/IModuleManifest';
export type { IModuleFlags } from './50-systems/ModuleStore/interfaces/IModuleManifest';
export type { IModuleManifestAuthor } from './50-systems/ModuleStore/interfaces/IModuleManifest';
export type { IModuleManifestSoftwareLicense } from './50-systems/ModuleStore/interfaces/IModuleManifest';
export type { IModuleManifestUsageLicense } from './50-systems/ModuleStore/interfaces/IModuleManifest';
export type { IModuleManifestUsageLicensePayed } from './50-systems/ModuleStore/interfaces/IModuleManifest';
export type { IModulePersister } from './50-systems/ModuleStore/interfaces/IModulePersister';
export type { IModuleSearchCriteria } from './50-systems/ModuleStore/interfaces/IModuleSearchCriteria';
export type { IModuleStatusReporter } from './50-systems/ModuleStore/interfaces/IModuleStatusReporter';
export type { IModuleStoreConnector } from './50-systems/ModuleStore/interfaces/IModuleStoreConnector';
export type { IModuleStoreConnectorSearchResult } from './50-systems/ModuleStore/interfaces/IModuleStoreConnectorSearchResult';
export type { IUrlVariables } from './50-systems/RoutingSystem/routePath/IUrlVariables';
export type { ISkin } from './50-systems/StyleSystem/ISkin';
export type { IStringMessage } from './50-systems/TranslationsSystem/interfaces/IMessage';
export type { IMessage } from './50-systems/TranslationsSystem/interfaces/IMessage';
export type { IBaseMessage } from './50-systems/TranslationsSystem/interfaces/IMessage';
export type { IFontStyleAttributeValue } from './70-attributes/FontStyleAttributeModule';
export type { IListStyle } from './71-arts/50-TextArt/interfaces/IListStyle';
export type { IBehavoirProps } from './72-tools/behaviors/IBehavoirProps';
