name: Publish new version

on:
    push:
        tags:
            - 'v*'

jobs:
    test:
        name: Test + Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 18
            - run: npm ci
            - run: npm run lint
            - run: npm run test

    publish-npm:
        name: Publish on NPM package registry
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
